version: '3'
services:
  # 服务名称
  eurekaServer:
    # 镜像:版本
    image: eurekadocker:eurekadocker
    # 映射容器80端口到本地80端口
    ports:
      - "8888:8888"
    environment:
      - spring.profiles.active=eurekaService
